# to create pdf report
from io import BytesIO
from reportlab.pdfgen import canvas
from django.http import HttpResponse
# to automate email
import email
import smtplib
import ssl
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# PDF

# name and create pdf
c = canvas.Canvas('automate_report.pdf')
# set background color (this color is yellow I do not recommend)
c.setFillColorRGB(1, 10, 0)
# Select font and font size
c.setFont('Helvetica', 30)
# create two text strings and set there position on the page
c.drawString(5, 660, 'Wellcome TO THE NEW WORLD!!')
c.drawString(5, 630, 'Report generated by MINNONORO')
# add an image determine it's position and width and height
c.drawImage('Survival.png', 5, 90, 480, 400)
# show page and save it
c.showPage()
c.save()


# MAIL SENT

# assign key email aspects to variables for easier future editing
subject = "Weekly Report"
body = "This is an email with the desired report attached"
sender_email = "connerleavitt@gmail.com"
receiver_email = "connerleavitt@icloud.com"
file = "automate_report.pdf"  # in the same directory as script
password = "abc123"
# Create the email head (sender, receiver, and subject)
email = MIMEMultipart()
email["From"] = sender_email
email["To"] = receiver_email
email["Subject"] = subject
# Add body and attachment to email
email.attach(MIMEText(body, "plain"))
attach_file = open(file, "rb")  # open the file
report = MIMEBase("application", "octate-stream")
report.set_payload((attach_file).read())
encoders.encode_base64(report)
# add report header with the file name
report.add_header("Content-Decomposition", "attachment", filename=file)
email.attach(report)
# Create SMTP session for sending the mail
session = smtplib.SMTP('smtp.gmail.com', 587)  # use gmail with port
session.starttls()  # enable security
session.login(sender_email, password)  # login with mail_id and password
text = email.as_string()
session.sendmail(sender_email, receiver_email, text)
session.quit()
print('Mail Sent')
